---
- name: Generate CA for Self Signed Certs
  hosts: zookeeper[0]
  tags: certificate_authority
  tasks:
  - import_role:
      name: confluent.variables_handlers

  - name: Create Certificate Authority and Copy to Ansible Host
    include_tasks: tasks/certificate_authority.yml
    when: (self_signed|bool and regenerate_ca|bool and kafka_broker_listeners | ssl_required(ssl_enabled)) or create_mds_certs|bool
- name: Host Prerequisites
  hosts: zookeeper:kafka_broker:schema_registry:kafka_connect:ksql:control_center:kafka_rest
  tags: common
  environment: "{{ proxy_env }}"
  tasks:
  - import_role:
      name: confluent.common

- name: Zookeeper Provisioning
  hosts: zookeeper
  tags: zookeeper
  environment: "{{ proxy_env }}"
  tasks:
  - import_role:
      name: confluent.zookeeper
      tasks_from: install

- name: Kafka Broker Provisioning
  hosts: kafka_broker
  tags: kafka_broker
  environment: "{{ proxy_env }}"
  tasks:
  - import_role:
      name: confluent.kafka_broker
      tasks_from: install

- name: Schema Registry Provisioning
  hosts: schema_registry
  tags: schema_registry
  environment: "{{ proxy_env }}"
  tasks:
  - import_role:
      name: confluent.schema_registry
      tasks_from: install

- name: Kafta Connect Provisioning
  hosts: kafka_connect
  tags: kafka_connect
  environment: "{{ proxy_env }}"
  tasks:
  - import_role:
      name: confluent.kafka_connect
      tasks_from: install

- name: KSQL Provisioning
  hosts: ksql
  tags: ksql
  environment: "{{ proxy_env }}"
  tasks:
  - import_role:
      name: confluent.ksql
      tasks_from: install

- name: Kafka Rest Provisioning
  hosts: kafka_rest
  tags: kafka_rest
  environment: "{{ proxy_env }}"
  tasks:
  - import_role:
      name: confluent.kafka_rest
      tasks_from: install

- name: Control Center Provisioning
  hosts: control_center
  tags: control_center
  environment: "{{ proxy_env }}"
  tasks:
  - import_role:
      name: confluent.control_center
      tasks_from: install
