---
- name: Zookeeper Provisioning
  hosts: zookeeper
  gather_facts: false
  tags: zookeeper
  tasks:
    - import_role: 
        name: confluent.zookeeper
        tasks_from: restart_zookeeper.yml

- name: Kafka Broker Provisioning
  hosts: kafka_broker
  gather_facts: false
  tags: kafka_broker
  tasks:
    - import_role: 
        name: confluent.kafka_broker
        tasks_from: restart_kafka.yml

- name: Schema Registry Provisioning
  hosts: schema_registry
  gather_facts: false
  tags: schema_registry
  tasks:
    - import_role:
        name: confluent.schema_registry
        tasks_from: restart_schema_registry.yml

- name: Kafta Connect Provisioning
  hosts: kafka_connect
  gather_facts: false
  tags: kafka_connect
  tasks:
    - import_role:
        name: confluent.kafka_connect
        tasks_from: restart_connect.yml

- name: KSQL Provisioning
  hosts: ksql
  gather_facts: false
  tags: ksql
  tasks:
    - import_role:
        name: confluent.ksql
        tasks_from: restart_ksql.yml

- name: Kafka Rest Provisioning
  hosts: kafka_rest
  gather_facts: false
  tags: kafka_rest
  tasks:
    - import_role:
        name: confluent.kafka_rest
        tasks_from: restart_kafka_rest.yml

- name: Control Center Provisioning
  hosts: control_center
  gather_facts: false
  tags: control_center
  tasks:
    - service:
        name: confluent-control-center
        state: restarted
