---
- include_role:
  name: confluent.common
when: not common_role_completed|bool

- name: Install the Kafka Broker Packages
yum:
  name: "{{item}}{{confluent_package_redhat_suffix}}"
  state: latest
loop: "{{kafka_broker_packages}}"
when: ansible_os_family == "RedHat"

- name: Install the Kafka Broker Packages
apt:
  name: "{{item}}{{confluent_package_debian_suffix}}"
loop: "{{kafka_broker_packages}}"
when: ansible_os_family == "Debian"